/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cg;

public class MoodAnalyzer {
	private String message;

	public MoodAnalyzer() {
	}

	public MoodAnalyzer(String message) {
		this.message = message;
	}

	public String analyseMood() {
		try {
			return message.toLowerCase().contains("sad") ? "SAD" : "HAPPY";
		}catch(Exception e) {
			System.out.println(e.getMessage());
			return "HAPPY";
		}
	}
}
