/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cg;

public class MoodAnalyzer {
	public String analyseMood(String message) {
		return message.toLowerCase().contains("sad") ? "SAD" : "HAPPY";
	}
}
