/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cg;

import org.junit.Test;

import com.cg.MoodAnalyzer;

import static org.junit.Assert.*;

import org.hamcrest.CoreMatchers;

public class MoodAnalyzerTest {

	@Test
	public void testCheckMoodHappy() {
		MoodAnalyzer moodAnalyzer = new MoodAnalyzer("I'm in Any Mood");
		assertEquals("HAPPY", moodAnalyzer.analyseMood());
	}

	@Test
	public void testCheckMoodSad() {
		MoodAnalyzer moodAnalyzer = new MoodAnalyzer("I'm in Sad Mood");
		assertEquals("SAD", moodAnalyzer.analyseMood());
	}
}
