/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cg;

import org.junit.Test;
import static org.junit.Assert.*;

public class MoodAnalyzerTest {

	@Test
	public void testAnalyseMoodSad() {
		MoodAnalyzer moodAnalyzer = new MoodAnalyzer("I'm in Sad Mood");
		assertEquals("SAD", moodAnalyzer.analyseMood());
	}

	@Test
	public void testAnalyseMoodHappy() {
		MoodAnalyzer moodAnalyzer = new MoodAnalyzer("I'm in Happy Mood");
		assertEquals("HAPPY", moodAnalyzer.analyseMood());
	}

	@Test
	public void testAnalyseMoodNull() {
		MoodAnalyzer moodAnalyzer = new MoodAnalyzer(null);
		assertEquals("HAPPY", moodAnalyzer.analyseMood());
	}
}
