/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cg;

import org.junit.Test;

import com.cg.MoodAnalyzer;

import static org.junit.Assert.*;

import org.hamcrest.CoreMatchers;

public class MoodAnalyzerTest {

	@Test
	public void testCheckMoodHappy() {
		MoodAnalyzer moodAnalyzer = new MoodAnalyzer();
		assertEquals("HAPPY", moodAnalyzer.analyseMood("I'm in Any Mood"));
	}

	@Test
	public void testCheckMoodSad() {
		MoodAnalyzer moodAnalyzer = new MoodAnalyzer();
		assertEquals("SAD", moodAnalyzer.analyseMood("I'm in Sad Mood"));
	}
}
